name: build
on:
  push:
jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler_family: gcc
            compiler_version: 11
          - compiler_family: gcc
            compiler_version: 12
          - compiler_family: llvm
            compiler_version: 13
          - compiler_family: llvm
            compiler_version: 14
          - compiler_family: llvm
            compiler_version: 15

    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3.3.0

      - name: Install compilers
        env:
          FAMILY: ${{ matrix.compiler_family }}
          VERSION: ${{ matrix.compiler_version }}
        run: |
          sudo add-apt-repository deb http://mirrors.mit.edu/ubuntu/ jammy-updates
          sudo apt-get update
          sudo apt-get install -y build-essential
          if [[ "${FAMILY}" == gcc ]]; then
              sudo apt install gcc-${VERSION} g++-${VERSION}
              echo "CC=gcc-${VERSION}" >> "$GITHUB_ENV"
              echo "CXX=g++-${VERSION}" >> "$GITHUB_ENV"
          elif [[ "${FAMILY}" == llvm ]]; then
              wget https://apt.llvm.org/llvm.sh
              chmod +x llvm.sh
              sudo ./llvm.sh ${VERSION} all
              echo "CC=clang-${VERSION}" >> "$GITHUB_ENV"
              echo "CXX=clang++-${VERSION}" >> "$GITHUB_ENV"
          else
              echo "[ERROR]: compiler family name not supported"
              exit -1
          fi

      # - name: Get GraphBLAS
      #   run: bash ./.github/workflows/get_graphblas.sh

      - name: Configure
        run: cmake -B build -DMTXIO_TEST=ON -DCMAKE_C_COMPILER=${{env.CC}} -DCMAKE_CXX_COMPILER=${{env.CXX}}

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build
